stages:
  - build
  - test
  - deploy

# variables:
#   MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
variables:
  DOCKER_USERNAME: $DOCKER_USERNAME
  DOCKER_PASSWORD: $DOCKER_PASSWORD
build:
  stage: build
  # before_script:
  #   - cd C:\Users\zeekouu\OneDrive\Bureau\GL\Assurence-BackEnd\Backend
#   image: maven:3.8.1-openjdk-11
  script:
    - mvn clean package
    - mvn package

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
#   image: docker:latest
  services:
    - docker:dind
  # before_script:
  #   # - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  #   - docker login --username zakibouarga --password ZekoZaki.2001

  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t back-assu:latest .
    - docker tag back-assu:latest zakibouarga/back-assu:latest
    - docker push zakibouarga/back-assu:latest
